### Create a new report 
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Ford",
    "model": "Ranger",
    "year": 2025,
    "mileage": 3000,
    "lng": 50,
    "lat": 50, 
    "price": 76000
}

### update report approval
PATCH http://localhost:3000/reports/2
content-type: application/json

{
    "approved": true
}

### get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=Ford&model=Ranger&year=2025&mileage=3000&lng=50&lat=50